---
title: "Einstellungstest_Hartwein"
author: "Alexander Hartwein"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
library(tidyverse)
library(knitr)


# package to combine ggplots

#install.packages("ggpubr")
library("ggpubr")
```

```{r}
df <- read.csv(file="raw_data/test.csv",sep=";",encoding = "latin1")
```

```{r}
tibble(df)
```



```{r}
studycourses_unique <- unique(df$Studiengang)
```

```{r}
for (i in studycourses_unique) {
  df_filtered <- df %>% filter(df$Studiengang== i)
  
  
 df_plot_qualitaet <- ggplot2::ggplot(df_filtered,aes(x=Qualität)) +
  ggtitle(paste0(df_filtered[1,1],"\n\n Qualität"))+
  ylab("Anzahl")+
  geom_bar()
 
 df_plot_verbleib <- ggplot2::ggplot(df_filtered,aes(x=Verbleib)) +
  ggtitle(paste0("Verbleib"))+
  ylab("Anzahl")+
  geom_bar()
 
 
 arrange <- ggarrange(
   df_plot_qualitaet, 
   df_plot_verbleib, 
   ncol = 1,
   nrow = 2)
 
 ggsave(paste0("outcome/",df_filtered[1,1],"- Plot.pdf"), arrange)

}
```


